language: cpp
dist: noble
compiler: gcc

git:
  submodules: false

install:
  - sudo apt-get update
  - sudo apt-get -y install -y libsdl2-dev
  - sudo apt-get -y install -y libsdl2-image-dev
  - sudo apt-get -y install -y libsdl2-mixer-dev
  - sudo apt-get -y install -y libzip-dev
  - sudo apt-get -y install -y liblua5.4-dev

script:
  - make
  - ./bin/pekka-kana-2 --version